source 'https://rubygems.org'

gem 'etc'
gem 'digest'
gem 'forwardable'
gem 'strscan'
gem 'stringio'
gem 'psych', '~> 4.0'
gem 'yaml'
gem 'pathname'
gem 'timeout'
gem 'english'
gem 'delegate'
gem 'weakref'
gem 'logger'
gem 'listen'
gem 'wdm'
gem 'singleton'
gem 'set'
gem 'tmpdir'
gem 'fileutils'
gem 'parallel'
gem 'open3'
gem 'rubyzip', '~> 2.3.2'
gem 'tempfile'
gem 'zlib'
gem 'seven_zip_ruby'
gem 'chunky_png'
