on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: Release

jobs:
  docker:
    name: Docker Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: enumag/eevee:${{ github.ref_name }}

  release:
    name: Release
    timeout-minutes: 30
    runs-on: windows-latest
    env:
      # https://github.com/Maher4Ever/wdm/issues/27
      BUNDLE_BUILD__WDM: "--with-cflags=-Wno-implicit-function-declaration"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Aibika
        run: gem install aibika

      - name: Version
        run: sed -i "s~\$VERSION = 'dev'~\$VERSION = '${{ github.ref_name }}'~g" eevee.rb

      - name: Compile
        run: >
          aibika
          eevee.rb
          src/*.rb
          rmxp/*.rb
          --gemfile Gemfile
          --gem-full
          --dll ruby_builtin_dlls\libyaml-0-2.dll
          --dll ruby_builtin_dlls\zlib1.dll
          --icon eevee.ico
          --output eevee.exe
          --no-dep-run
          --no-lzma

      - name: Archive
        run: zip --junk-paths modding-tools-${{ github.ref_name }}.zip eevee.exe DOCS.md example/* example/.*

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: modding-tools-${{ github.ref_name }}.zip
